DROP TABLE IF EXISTS users, quotes;

CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     email VARCHAR(32) NOT NULL,
                                     login VARCHAR(16) NOT NULL,
                                     password VARCHAR(32) NOT NULL,
                                     created TIMESTAMP WITHOUT TIME ZONE,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS quotes (
                                      id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                      content VARCHAR(255) NOT NULL,
                                      owner_id BIGINT,
                                      votes BIGINT,
                                      last_update TIMESTAMP WITHOUT TIME ZONE,
                                      CONSTRAINT fk_quotes_to_users FOREIGN KEY(owner_id) REFERENCES users(id),
                                      UNIQUE (id)
);